language: shell
os: linux
arch: amd64
dist: bionic

services: docker

branches:
  only:
    - master

before_install:
  - docker-compose --version
  - docker --version

env:
  - VERSION=v2
  - VERSION=v3

script:
  - cd $VERSION && docker-compose up --build --exit-code-from iperf${VERSION}-for-android
